name: Brandon++
description: A Minecraft plugin for commending the achievements of my colleague and good friend Brandon.
author: ALargeBagel (Aaron Tello-Wharton)
main: uk.tellowharton.mc.brandon.Congrats
version: 1.0